<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../J113D.ProjectConfigurations/NuGet.Build.props" />
	
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>J113D.UndoRedo</RootNamespace>
	</PropertyGroup>


	<PropertyGroup>
		<Title>J113D UndoRedo Library</Title>
		<Product>J113D UndoRedo Library</Product>
		<Description>A versatile UndoRedo library</Description>
		<Version>1.1.0</Version>
		<RepositoryUrl>https://github.com/Justin113D/J113D.UndoRedo</RepositoryUrl>
		<PackageProjectUrl>https://github.com/Justin113D/J113D.UndoRedo</PackageProjectUrl>
		<PackageId>J113D.UndoRedo</PackageId>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>


	<ItemGroup>
	  <None Remove="PublicAPI\net10.0\PublicAPI.Shipped.txt" />
	  <None Remove="PublicAPI\net10.0\PublicAPI.Unshipped.txt" />
	</ItemGroup>
	
	<ItemGroup>
		<None Include="../../README.md" Pack="true" PackagePath="" />
	</ItemGroup>

</Project>
